import {formatNumberByThresholds, Threshold} from "./threshold.strategy";

const thresholds: Threshold[] = [
  {value: 1e108, suffix: "Qitg"},
  {value: 1e105, suffix: "Qatg"},
  {value: 1e102, suffix: "Ttg"},
  {value: 1e99, suffix: "Dtg"},
  {value: 1e96, suffix: "Utg"},
  {value: 1e93, suffix: "Tg"},
  {value: 1e90, suffix: "Novg"},
  {value: 1e87, suffix: "Ocvg"},
  {value: 1e84, suffix: "Spvg"},
  {value: 1e81, suffix: "Sxvg"},
  {value: 1e78, suffix: "Qivg"},
  {value: 1e75, suffix: "Qavg"},
  {value: 1e72, suffix: "Tvg"},
  {value: 1e69, suffix: "Dvg"},
  {value: 1e66, suffix: "Uvg"},
  {value: 1e63, suffix: "Vg"},
  {value: 1e60, suffix: "Nod"},
  {value: 1e57, suffix: "Ocd"},
  {value: 1e54, suffix: "Spd"},
  {value: 1e51, suffix: "Sxd"},
  {value: 1e48, suffix: "Qid"},
  {value: 1e45, suffix: "Qad"},
  {value: 1e42, suffix: "Td"},
  {value: 1e39, suffix: "Dd"},
  {value: 1e36, suffix: "Ud"},
  {value: 1e33, suffix: "Dc"},
  {value: 1e30, suffix: "No"},
  {value: 1e27, suffix: "Oc"},
  {value: 1e24, suffix: "Sp"},
  {value: 1e21, suffix: "Sx"},
  {value: 1e18, suffix: "Qi"},
  {value: 1e15, suffix: "Qa"},
  {value: 1e12, suffix: "T"},
  {value: 1e9, suffix: "B"},
  {value: 1e6, suffix: "M"},
  {value: 1e3, suffix: "k"},
  {value: 1, suffix: ""},
];

export function formatNumberBySystemTerraformationIndexThresholds(value: number | bigint) {
  return formatNumberByThresholds(value, thresholds);
}
