entry = [
    "packages/cli-merge/cli/merge-cli.js",
    "packages/cli-validate/cli/validate-cli.js",
    "packages/ui-save-manager/src/entry-client.tsx",
    "packages/ui-save-manager/src/entry-server.tsx",
    "packages/**/*.spec.js",
    "packages/**/*.spec.ts",
    "testSetup.ts",
    "packages/*/testSetup.ts",
    "testIsolation.spec.ts",
]

ignorePatterns = [
    "output/**",
    "input/**",
    "packages/ui-save-manager/**",
]

ignoreDependencies = [
    "bun",
    "@types/bun",
    "typescript",
    "ui-save-manager"
]

ignoreUnresolvedImports = [
    "shared-save-processing/schemas/section0-player-progression.schema.json",
    "shared-save-processing/schemas/section1-terraformation-levels.schema.json",
    "shared-save-processing/schemas/section2-players.schema.json",
    "shared-save-processing/schemas/section4-inventories.schema.json",
    "shared-save-processing/schemas/section5-statistics.schema.json",
    "shared-save-processing/schemas/section6-messages.schema.json",
    "shared-save-processing/schemas/section7-story-events.schema.json",
    "shared-save-processing/schemas/section8-save-config.schema.json",
    "shared-save-processing/schemas/section9-world-events.schema.json",
]

[audit]
gate = "new-only"

[health]


[rules]
unused-files = "error"
unused-exports = "warn"
unused-types = "warn"
unresolved-imports = "error"
