import Ajv from 'ajv';
import standaloneCode from 'ajv/dist/standalone';
import schema0 from 'shared-save-processing/schemas/section0-player-progression.schema.json' with {type: 'json'};
import schema1 from 'shared-save-processing/schemas/section1-terraformation-levels.schema.json' with {type: 'json'};
import schema2 from 'shared-save-processing/schemas/section2-players.schema.json' with {type: 'json'};
import schema3 from 'shared-save-processing/schemas/section3-world-objects.schema.json' with {type: 'json'};
import schema4 from 'shared-save-processing/schemas/section4-inventories.schema.json' with {type: 'json'};
import schema5 from 'shared-save-processing/schemas/section5-statistics.schema.json' with {type: 'json'};
import schema6 from 'shared-save-processing/schemas/section6-messages.schema.json' with {type: 'json'};
import schema7 from 'shared-save-processing/schemas/section7-story-events.schema.json' with {type: 'json'};
import schema8 from 'shared-save-processing/schemas/section8-save-config.schema.json' with {type: 'json'};
import schema9 from 'shared-save-processing/schemas/section9-world-events.schema.json' with {type: 'json'};
import legacyTerrainLayersSchema from 'shared-save-processing/schemas/legacy-section9-terrain-layers.schema.json' with {type: 'json'};

const SECTION_SCHEMAS = [schema0, schema1, schema2, schema3, schema4, schema5, schema6, schema7, schema8, schema9, legacyTerrainLayersSchema];

export const SECTION_VALIDATORS_PATH = new URL('../src/infrastructure/sectionValidators.generated.js', import.meta.url).pathname;

const GENERATED_MODULE_HEADER = '// @ts-nocheck\n// fallow-ignore-file complexity\n// Generated by bun run generate:section-validators from the JSON Schemas of shared-save-processing.\n';

function resolveValidatorExportName(schemaId: string): string {
  const schemaName = schemaId.replace('.schema.json', '');

  return `validate${schemaName.split('-').map(word => word[0].toUpperCase() + word.slice(1)).join('')}`;
}

export function generateSectionValidatorsSource(): string {
  const ajv = new Ajv({code: {source: true, esm: true}});
  const schemaIdsByExportName: Record<string, string> = {};
  for (const sectionSchema of SECTION_SCHEMAS) {
    ajv.addSchema(sectionSchema, sectionSchema.$id);
    schemaIdsByExportName[resolveValidatorExportName(sectionSchema.$id)] = sectionSchema.$id;
  }
  const validatorsByIdEntries = Object.entries(schemaIdsByExportName)
    .map(([exportName, schemaId]) => `  '${schemaId}': ${exportName}`)
    .join(',\n');

  const validatorsSource = standaloneCode(ajv, schemaIdsByExportName).replaceAll('export const ', 'const ');

  return `${GENERATED_MODULE_HEADER}${validatorsSource}\n\nexport const SECTION_VALIDATORS_BY_SCHEMA_ID = {\n${validatorsByIdEntries}\n};\n`;
}

if (import.meta.main) {
  await Bun.write(SECTION_VALIDATORS_PATH, generateSectionValidatorsSource());
}
