import Ajv from 'ajv';
import standaloneCode from 'ajv/dist/standalone';
import {runAsEntryPoint, type SectionValidatorsFileIo} from './sectionValidatorsFile.ts';
import schema0 from '../src/save/infrastructure/wireFormat/schemas/section0-player-progression.schema.json' with {type: 'json'};
import schema1 from '../src/save/infrastructure/wireFormat/schemas/section1-terraformation-levels.schema.json' with {type: 'json'};
import schema2 from '../src/save/infrastructure/wireFormat/schemas/section2-players.schema.json' with {type: 'json'};
import schema3 from '../src/save/infrastructure/wireFormat/schemas/section3-world-objects.schema.json' with {type: 'json'};
import schema4 from '../src/save/infrastructure/wireFormat/schemas/section4-inventories.schema.json' with {type: 'json'};
import schema5 from '../src/save/infrastructure/wireFormat/schemas/section5-statistics.schema.json' with {type: 'json'};
import schema6 from '../src/save/infrastructure/wireFormat/schemas/section6-messages.schema.json' with {type: 'json'};
import schema7 from '../src/save/infrastructure/wireFormat/schemas/section7-story-events.schema.json' with {type: 'json'};
import schema8 from '../src/save/infrastructure/wireFormat/schemas/section8-save-config.schema.json' with {type: 'json'};
import schema9 from '../src/save/infrastructure/wireFormat/schemas/section9-world-events.schema.json' with {type: 'json'};
import legacyTerrainLayersSchema from '../src/save/infrastructure/wireFormat/schemas/legacy-section9-terrain-layers.schema.json' with {type: 'json'};

const SECTION_SCHEMAS = [schema0, schema1, schema2, schema3, schema4, schema5, schema6, schema7, schema8, schema9, legacyTerrainLayersSchema];

const GENERATED_MODULE_HEADER = '// @ts-nocheck\n// fallow-ignore-file complexity\n// Generated by bun run generate:section-validators from the JSON Schemas of the save wire format.\n';

function resolveValidatorExportName(schemaId: string): string {
  const schemaName = schemaId.replace('.schema.json', '');

  return `validate${schemaName.split('-').map(word => word[0].toUpperCase() + word.slice(1)).join('')}`;
}

export function generateSectionValidatorsSource(): string {
  const ajv = new Ajv({code: {source: true, esm: true}});
  const schemaIdsByExportName: Record<string, string> = {};
  for (const sectionSchema of SECTION_SCHEMAS) {
    ajv.addSchema(sectionSchema, sectionSchema.$id);
    schemaIdsByExportName[resolveValidatorExportName(sectionSchema.$id)] = sectionSchema.$id;
  }
  const validatorsByIdEntries = Object.entries(schemaIdsByExportName)
    .map(([exportName, schemaId]) => `  '${schemaId}': ${exportName}`)
    .join(',\n');

  const validatorsSource = standaloneCode(ajv, schemaIdsByExportName).replaceAll('export const ', 'const ');

  return `${GENERATED_MODULE_HEADER}${validatorsSource}\n\nexport const SECTION_VALIDATORS_BY_SCHEMA_ID = {\n${validatorsByIdEntries}\n};\n`;
}

export async function generateSectionValidators(io: SectionValidatorsFileIo): Promise<void> {
  await io.writeVersionedSource(generateSectionValidatorsSource());
}

await runAsEntryPoint(import.meta.main, generateSectionValidators);
