const OUTPUT_DIR = 'output';
const INPUT_SUBFOLDER_ALPHA = 'Alpha';
const MERGED_SAVE_OUTPUT_PATH = `${OUTPUT_DIR}/${INPUT_SUBFOLDER_ALPHA}/Standard-1-Standard-2-merged.json`;
export const VALIDATE_SAVE_FILE_PATH = MERGED_SAVE_OUTPUT_PATH;
