import {LoadConfigurationPageController} from "../controllers/LoadConfigurationPageController";
import {LoadPowerPageController} from "../controllers/LoadPowerPageController";
import {LoadPlayersMenuController} from "../controllers/LoadPlayersMenuController";
import {LoadSaveIdentityController} from "../controllers/LoadSaveIdentityController";
import {LoadTerraformationPageController} from "../controllers/LoadTerraformationPageController";
import {createLoadConfigurationPage, createLoadPowerPage, createLoadPlayersMenu, createLoadSaveIdentity, createLoadTerraformationPage} from "./useCaseFactories";
import {LoadOverviewPageController} from "../controllers/LoadOverviewPageController";
import {createLoadOverviewPage} from "./useCaseFactories";
import {LoadPlayersPageController} from "../controllers/LoadPlayersPageController";
import {createLoadPlayersPage} from "./useCaseFactories";
import {LoadPlanetPageController} from "../controllers/LoadPlanetPageController";
import {createLoadPlanetPage} from "./useCaseFactories";

export const loadConfigurationPageController = new LoadConfigurationPageController(createLoadConfigurationPage);
export const loadPowerPageController = new LoadPowerPageController(createLoadPowerPage);
export const loadPlayersMenuController = new LoadPlayersMenuController(createLoadPlayersMenu);
export const loadSaveIdentityController = new LoadSaveIdentityController(createLoadSaveIdentity);
export const loadTerraformationPageController = new LoadTerraformationPageController(createLoadTerraformationPage);
export const loadOverviewPageController = new LoadOverviewPageController(createLoadOverviewPage);
export const loadPlayersPageController = new LoadPlayersPageController(createLoadPlayersPage);
export const loadPlanetPageController = new LoadPlanetPageController(createLoadPlanetPage);
