export {
  GLOBAL_METADATA_SECTION,
  INVENTORIES_SECTION,
  LEGACY_RESERVED_TRAILING_PART,
  LEGACY_TERRAIN_LAYERS_SECTION,
  LEGACY_WORLD_EVENTS_SECTION,
  MAILBOX_MESSAGES_SECTION,
  PLAYERS_SECTION,
  RESERVED_TRAILING_PART,
  WORLD_EVENTS_SECTION,
  WORLD_OBJECTS_SECTION
} from "../infrastructure/testing/saveSectionLocations";
