export const worldObjectLabels = {
  // Equipment
  BootsSpeed1: 'Agility Boots T1',
  BootsSpeed2: 'Agility Boots T2',
  BootsSpeed3: 'Agility Boots T3',
  Backpack1: 'Backpack T1',
  Backpack2: 'Backpack T2',
  Backpack3: 'Backpack T3',
  Backpack4: 'Backpack T4',
  Backpack5: 'Backpack T5',
  Backpack6: 'Backpack T6',
  Backpack7: 'Backpack T7',
  EquipmentIncrease1: 'Exoskeleton T1',
  EquipmentIncrease2: 'Exoskeleton T2',
  EquipmentIncrease3: 'Exoskeleton T3',
  EquipmentIncrease4: 'Exoskeleton T4',
  EquipmentIncrease5: 'Exoskeleton T5',
  EquipmentIncrease6: 'Exoskeleton T6',
  EquipmentIncrease7: 'Exoskeleton T7',
  Jetpack1: 'Jetpack T1',
  Jetpack2: 'Jetpack T2',
  Jetpack3: 'Jetpack T3',
  Jetpack4: 'Jetpack T4',
  Jetpack5: 'Jetpack T5',
  AirFilter1: 'Air filter',
  WaterFilter: 'Water Filter',
  HudCompass: 'Microchip - Compass',
  MapChip: 'Microchip - Map',
  MultiBuild: 'Microchip - Construction',
  MultiDeconstruct: 'Microchip - Deconstruction T1',
  MultiToolDeconstruct2: 'Microchip - Deconstruction T2',
  MultiToolDeconstruct3: 'Microchip - Deconstruction T3',
  MultiToolMineSpeed1: 'Microchip - Mining speed T1',
  MultiToolMineSpeed2: 'Microchip - Mining speed T2',
  MultiToolMineSpeed3: 'Microchip - Mining speed T3',
  MultiToolMineSpeed4: 'Microchip - Mining speed T4',
  MultiToolLight2: 'Microchip – Torch T2',
  MultiToolLight: 'Microchip - Torch',
  PinChip1: 'Microchip - Pin T1',
  PinChip2: 'Microchip - Pin T2',
  PinChip3: 'Microchip - Pin T3',
  OxygenTank1: 'Oxygen tank T1',
  OxygenTank2: 'Oxygen tank T2',
  OxygenTank3: 'Oxygen tank T3',
  OxygenTank4: 'Oxygen tank T4',
  OxygenTank5: 'Oxygen tank T5',
  // Crafting
  CraftStation1: 'Craft station T2',
  CraftStation2: 'Advanced Craft Station',
  GeneticManipulator1: 'DNA Manipulator',
  Incubator1: 'Incubator',
  // Ores
  Aluminium: 'Aluminium',
  Bioplastic1: 'Bioplastic nugget',
  Cobalt: 'Cobalt',
  ice: 'Ice',
  Iridium: 'Iridium',
  Iron: 'Iron',
  Magnesium: 'Magnesium',
  Osmium: 'Osmium',
  PulsarQuartz: 'Pulsar Quartz',
  BalzarQuartz: 'Blazar Quartz',
  MagnetarQuartz: 'Magnetar Quartz',
  QuasarQuartz: 'Quasar Quartz',
  SolarQuartz: 'Solar Quartz',
  Silicon: 'Silicon',
  Sulfur: 'Sulfur',
  Titanium: 'Titanium',
  Uranim: 'Uranium',
  Zeolite: 'Zeolite',
  // Resource generators
  AlgaeGenerator1: 'Algae Generator T1',
  AlgaeGenerator2: 'Algae Generator T2',
  WaterCollector1: 'Atmospheric Water Collector',
  VegetableGrower1: 'Food grower',
  VegetableGrower2: 'Food grower T2',
  GasExtractor1: 'Gas Extractor',
  Vegetube1: 'Vegetube T1',
  Vegetube2: 'Vegetube T2',
  VegetubeOutside1: 'Vegetube T3',
  WaterCollector2: 'Lake Water Collector',
  OreExtractor2: 'Ore Extractor T2',
  OreExtractor1: 'Ore Extractor',
  Beehive1: 'Bee Hive',
  ButterflyFarm1: 'Butterfly Farm',
  Farm1: 'Outdoor Farm',
  SilkGenerator: 'Silk Generator',
  // Rockets
  EscapePod: 'Escape pod',
  RocketBiomass1: 'Biomass Rocket',
  RocketHeat1: 'Asteroids attraction rocket',
  RocketMap1: 'GPS satellite T1',
  RocketMap2: 'GPS satellite T2',
  RocketMap3: 'GPS satellite T3',
  RocketPressure1: 'Magnetic field protection rocket',
  RocketInformations1: 'Map information rocket',
  RocketOxygen1: 'Seeds spreader rocket',
  // Organic resources
  Algae1Seed: 'Algae',
  Algae1Growable: 'Algae1Growable',
  Bacteria1: 'Bacteria Sample',
  Vegetable0Seed: 'Eggplant seeds',
  Vegetable0Growable: 'Eggplant',
  Vegetable2Seed: 'Beans seeds',
  Vegetable2Growable: 'Beans',
  Tree0Growable: 'Tree0Growable',
  Tree1Growable: 'Tree1Growable',
  Tree2Growable: 'Tree2Growable',
  Tree3Growable: 'Tree3Growable',
  Tree4Growable: 'Tree4Growable',
  Tree5Growable: 'Tree5Growable',
  Tree6Growable: 'Tree6Growable',
  Tree7Growable: 'Tree7Growable',
  Tree8Growable: 'Tree8Growable',
  TreeRoot: 'Tree bark',
  Vegetable1Seed: 'Squash seeds',
  Vegetable1Growable: 'Squash',
  Vegetable3Seed: 'Mushroom seeds',
  Vegetable3Growable: 'Mushroom',
  SeedGoldGrowable: 'Plant Golden',
  Seed0Growable: 'Plant Lirma',
  Seed3Growable: 'Plant Nulna',
  Seed2Growable: 'Plant Pestera',
  Seed1Growable: 'Plant Shanga',
  Seed4Growable: 'Plant Tuska',
  Seed5Growable: 'Seed5Growable',
  Seed6Growable: 'Seed6Growable',
  Seed7Growable: 'Seed7Growable',
  Seed8Growable: 'Seed8Growable',
  Seed9Growable: 'Seed9Growable',
  Silk: 'Silk',
  Phytoplankton1: 'Phytoplankton A',
  Phytoplankton2: 'Phytoplankton B',
  Phytoplankton3: 'Phytoplankton C',
  // Craftable resources
  Alloy: 'Super Alloy',
  RedPowder1: 'Explosive powder',
  FabricBlue: 'Fabric',
  Fertilizer2: 'Fertilizer T2',
  Fertilizer1: 'Fertilizer',
  FusionEnergyCell: 'Fusion Energy Cell',
  'Rod-Iridium': 'Iridium Rod',
  'Rod-alloy': 'Super Alloy Rod',
  'Rod-uranium': 'Uranium Rod',
  'Rod-osmium': 'Osmium Rod',
  Mutagen1: 'Mutagen',
  Mutagen2: 'Mutagen2',
  Mutagen3: 'Mutagen3',
  Mutagen4: 'Mutagen4',
  OxygenCapsule1: 'Oxygen capsule',
  WaterBottle1: 'Water bottle',
  SpaceMultiplierHeat: 'Space heat multiplier',
  SpaceMultiplierOxygen: 'Space oxygen multiplier',
  SpaceMultiplierPressure: 'Space pressure multiplier',
  SpaceMultiplierBiomass: 'SpaceMultiplierBiomass',
  RocketReactor: 'Rocket Engine',
  // Fuses
  FusePressure1: 'Pressure Fuse',
  FuseHeat1: 'Heat Fuse',
  FusePlants1: 'Plants Fuse',
  FuseOxygen1: 'Oxygen Fuse',
  FuseAnimals1: 'Animals Fuse',
  FuseEnergy1: 'Energy Fuse',
  FuseGrowth1: 'Growth Fuse',
  FuseInsects1: 'Insects Fuse',
  FuseProduction1: 'Production Fuse',
  FuseTradeRocketsSpeed1: 'Trade Rockets Speed Fuse',
  // Decoration
  InsideLamp1: 'Area Lamp',
  Beacon: 'Beacon',
  BedSimple: 'Bed',
  canister: 'canister',
  Chair1: 'Chair',
  Desktop1: 'Desktop',
  DisplayCase: 'Display case',
  BedDouble: 'Double Bed',
  Foundation: 'Foundation grid',
  GoldenContainer: 'Golden Crate',
  GoldenEffigie1: 'Golden effigie',
  GoldenEffigie2: 'Golden effigie',
  GoldenEffigie3: 'Golden effigie',
  GoldenEffigieSpawner: 'GoldenEffigieSpawner',
  Ladder: 'Indoor Ladder',
  door: 'Living compartment door',
  FloorGlass: 'Living compartment glass',
  'window': 'Living compartment window',
  OutsideLamp1: 'Outside lamp',
  Stairs: 'Outside Stairs',
  wallplain: 'Plain wall',
  Sign: 'Sign',
  SofaAngle: 'Sofa angle',
  Sofa: 'Sofa',
  TableSmall: 'Table',
  Pooltable1: 'Pool Table',
  FlowerPot1: 'Flower Pot',
  FlowerPot2: 'Hanging Flower Pot',
  FlowerPot3: 'Big Flower Pot',
  SofaAngleColored: 'Customizable Corner Sofa',
  TreePlanter2: 'Bonzai Pot',
  TableSmall2: 'Small table',
  Ivy1: 'Ivy',
  ButterflyDisplayer1: 'Butterfly Display Box',
  Server1: 'Server',
  // Compartments
  Pod4x: 'Big living compartment',
  biodome: 'Biodome',
  Biodome2: 'Biodome T2',
  Biolab: 'Biolab',
  ButterflyDome1: 'Butterfly Dome',
  podAngle: 'Living compartment corner',
  pod: 'Living compartment',
  // Base machines
  ComAntenna: 'Communication Antenna',
  Drill0: 'Drill T1',
  Drill1: 'Drill T2',
  Drill2: 'Drill T3',
  Drill3: 'Drill T4',
  FusionGenerator1: 'Fusion reactor',
  GrassSpreader1: 'Grass spreader',
  Heater1: 'Heater T1',
  Heater2: 'Heater T2',
  Heater3: 'Heater T3',
  Heater4: 'Heater T4',
  SeedSpreader2: 'Flower Spreader T2',
  SeedSpreader1: 'Flower Spreader',
  TreeSpreader1: 'Tree spreader T2',
  TreeSpreader2: 'Tree spreader T3',
  TreeSpreader0: 'Tree spreader',
  TreeSpreaderGiant: 'TreeSpreaderGiant',
  Teleporter1: 'Teleporter',
  EnergyGenerator1: 'Wind turbine',
  EnergyGenerator2: 'Solar panel T1',
  EnergyGenerator3: 'Solar panel T2',
  EnergyGenerator4: 'Nuclear Reactor T1',
  EnergyGenerator5: 'Nuclear Reactor T2',
  EnergyGenerator6: 'Nuclear Fusion generator',
  RecyclingMachine: 'Recycling machine',
  ScreenUnlockables: 'Screen - Blueprints',
  ScreenEnergy: 'Screen - Energy levels',
  ScreenMap1: 'Screen - Mapping',
  ScreenRockets: 'Screen – Orbital informations',
  ScreenTerraStage: 'Screen - Progress',
  ScreenTerraformation: 'Screen - Terraformation',
  ScreenMessage: 'Screen - Transmissions',
  Destructor1: 'Shredder machine',
  Drone1: 'Drone T1',
  Drone2: 'Drone T2',
  // Seeds
  Seed0: 'Seed Lirma',
  Seed1: 'Seed Shanga (150%)',
  Seed2: 'Seed Pestera (200%)',
  Seed3: 'Seed Nula (300%)',
  Seed4: 'Seed Tuska (400%)',
  Seed5: 'Seed Orema (450%)',
  Seed6: 'Seed Volnus (500%)',
  Seed7Humble: 'Snepea Seed (unknown bonus)',
  Seed8Humble: 'Brelea Seed (unknown bonus)',
  Seed9Humble: 'Seleus Seed (unknown bonus)',
  SeedGold: 'Golden Seed (600%)',
  CookWheatSeed: 'Wheat Seed',
  CookCocoaSeed: 'Cocoa Seed',
  // Tree seeds
  Tree0Seed: 'TreeSeed Iterra (125%)',
  Tree1Seed: 'Tree Seed Linifolia (125%)',
  Tree2Seed: 'Tree Seed Aleatus (125%)',
  Tree3Seed: 'Tree Seed Cernea (150%)',
  Tree4Seed: 'Tree Seed Elegea (175%)',
  Tree5Seed: 'Tree Seed Humelora (250%)',
  Tree6Seed: 'Tree Seed Aemora (400%)',
  Tree7Seed: 'Tree Seed Pleom (350%)',
  Tree8Seed: 'Tree Seed Soleus(125%)',
  Tree9Seed: 'Tree Seed Shreox (450%)',
  Tree10Seed: 'Tree Seed Rosea (600%)',
  // Larvae
  LarvaeBase1: 'Common Larva',
  LarvaeBase2: 'Uncommon Larva',
  LarvaeBase3: 'Rare Larva',
  Bee1Larvae: 'Bee Larva',
  SilkWorm: 'Silk Worm',
  Butterfly1Larvae: 'ButterflyAzurae Larva (120%)',
  Butterfly2Larvae: 'Butterfly Leani Larva (175%)',
  Butterfly3Larvae: 'Butterfly Fensea Larva (200%)',
  Butterfly4Larvae: 'Butterfly Galaxe Larva (175%)',
  Butterfly5Larvae: 'Butterfly Abstreus Larva (175%)',
  Butterfly6Larvae: 'Butterfly Empalio Larva (120%)',
  Butterfly7Larvae: 'Butterfly Penga Larva (230%)',
  Butterfly8Larvae: 'Butterfly Chevrone (250%)',
  Butterfly9Larvae: 'Butterfly Aemel Larva (300%)',
  Butterfly10Larvae: 'Butterfly Liux Larva (500%)',
  Butterfly11Larvae: 'Butterfly Nere Larva (600%)',
  Butterfly12Larvae: 'Butterfly Lorpen Larva (600%)',
  Butterfly13Larvae: 'Butterfly Fiorente (600%)',
  Butterfly14Larvae: 'Butterfly Alben Larva (700%) – solidblack',
  Butterfly15Larvae: 'Butterfly Futura Larva (800%) –GLOWS Pink',
  Butterfly16Larvae: 'Butterfly Imeo Larva (1000%)',
  Butterfly17Larvae: 'Butterfly Serena Larva (1200%)',
  Butterfly18Larvae: 'Butterfly Golden Larva (1500%) –GLOWS Gold',
  Butterfly19Larvae: 'Butterfly Faleria Eggs (1400%)',
  // Fish eggs
  Fish1Eggs: 'Provios Eggs (100%)',
  Fish2Eggs: 'Vilnus Eggs (150%)',
  Fish3Eggs: 'Gerrero Eggs (150%)',
  Fish4Eggs: 'Khrom Eggs (200%)',
  Fish5Eggs: 'Ulani Eggs (250%)',
  Fish6Eggs: 'Aelera Eggs (300%)',
  Fish7Eggs: 'Tegede Eggs (300%)',
  Fish8Eggs: 'Ecaru Eggs (325%)',
  Fish9Eggs: 'Buyu Eggs (350%)',
  Fish10Eggs: 'Tiloo Eggs (400%)',
  Fish11Eggs: 'Golden Fish Eggs (500%)',
  // Frog eggs
  Frog1Eggs: 'Generic Frog Eggs(100%)',
  Frog2Eggs: 'Huli Eggs (150%)',
  Frog3Eggs: 'Felicianna Eggs(200%)',
  Frog4Eggs: 'Strabo Eggs (200%)',
  Frog5Eggs: 'Trajuu Eggs (300%)',
  Frog6Eggs: 'Aiolus Eggs (250%)',
  Frog7Eggs: 'Afae Eggs (350%)',
  Frog8Eggs: 'Cillus Eggs (350%)',
  Frog9Eggs: 'Amedo Eggs (400%)',
  Frog10Eggs: 'Kenjoss Eggs (500%)',
  FrogGoldenEggs: 'Golden Frog Eggs (600%)',
  // Lockers
  Container1: 'Storage crate',
  Container2: 'Locker Storage',
  // Blueprints
  BlueprintT1: 'Blueprint microchip',
  BlueprintDeparturePlatform: 'Extraction Platform',
  BlueprintTradePlatform: 'Trade Platform',
  BlueprintSofaColored: 'Customizable Sofa',
  BlueprintSmartFabric: 'Smart Fabric',
  BlueprintCookingStation: 'Cooking Station',
  BlueprintBedDoubleColored: 'Customizable Bed',
  BlueprintContainer3: 'T2 Locker Storage',
  BlueprintDrone2: 'T2 Drone',
  BlueprintPod9xA: 'Rounded Living Compartment',
  BlueprintPod9xB: 'Living Compartment with Dome',
  BlueprintPod9xC: '3x3 Living Compartment',
  BlueprintFountainBig: 'Fountain',
  BlueprintHologramGenerator: 'Hologram Projector',
  // Terra tokens
  TerraTokens100: '100 Terra Tokens',
  TerraTokens500: '500 Terra Tokens',
  TerraTokens1000: '1000 Terra Tokens',
  TerraTokens5000: '5000 Terra Tokens',
  // Other
  Keycard1: 'Access card',
  LaunchPlatform: 'Launch Platform',
  MethanCapsule1: 'Methane cartridge',
  astrofood: 'Space Food',
  PulsarShard: 'Pulsar Quartz Shard',
  PulsarChip: 'PulsarChip',
  wreckpilar: 'Wrecks',
  WardenKey: 'Warden\'s key',
  AirPurificationMachine1T1: 'Atmosphere purifier T1',
  AirPurificationMachine2T2: 'Atmosphere purifier T2',
  AirPurificationMachine3T3: 'Atmosphere purifier T3',
  AirPurificationMachine4T4: 'Atmosphere purifier T4',
  AlgaeGenerator1T1: 'Algae Generator T1',
  AlgaeGenerator2T2: 'Algae Generator T2',
  AmphibiansFarm1Amphibian: 'Amphibians Farm',
  AnimalEffigie1Animal: 'Effigy : Sharky',
  AnimalEffigie2Animal: 'Effigy : Allyca',
  AnimalEffigie3Animal: 'Effigy : Tilopina',
  AnimalEffigie4Animal: 'Effigy : Snoober',
  AnimalEffigie5Animal: 'Effigy : Muthus',
  AnimalEffigie6Animal: 'Effigy : Hydrequus',
  AnimalEffigie7Animal: 'Effigy : Arbatillo',
  AnimalEffigie8Animal: 'Effigy : Carachnid',
  AnimalEffigie9Animal: 'Effigy : Doggox',
  AnimalFeeder1: 'Animal feeder',
  AnimalFood1: 'Animal food T1',
  AnimalFood2: 'Animal food T2',
  AnimalFood3: 'Animal food T3',
  AnimalShelter1: 'Animal shelter',
  AntiToxinsExplosive1T1: 'Toxic goo removal explosives T1',
  AntiToxinsExplosive2T2: 'Toxic goo removal explosives T2',
  Aquarium1: 'Aquarium T1',
  Aquarium2: 'Aquarium T2',
  astrofood2: 'High quality Space Food',
  AutoCrafter1: 'Auto Crafter',
  Bauxite: 'Bauxite',
  BedDoubleColored: 'Customizable bed',
  Bee1Hatched: 'Bee1Hatched',
  Beehive2: 'Beehive T2',
  BlueprintAutocrafter: 'BlueprintAutocrafter',
  BlueprintEquipmentIncrease2: 'BlueprintEquipmentIncrease2',
  BlueprintEquipmentIncrease5: 'BlueprintEquipmentIncrease5',
  BlueprintFireplace: 'BlueprintFireplace',
  BlueprintFlare: 'BlueprintFlare',
  BlueprintLightBoxMedium: 'BlueprintLightBoxMedium',
  BlueprintSolarQuartz: 'BlueprintSolarQuartz',
  BlueprintToxicityDiorama1: 'Blueprint Toxicity Diorama 1',
  BlueprintToxicityDiorama2: 'Blueprint Toxicity Diorama 2',
  BlueprintTreePlanter: 'BlueprintTreePlanter',
  BlueprintWardensChip: 'BlueprintWardensChip',
  Butterfly10Hatched: 'Butterfly10Hatched',
  Butterfly11Hatched: 'Butterfly11Hatched',
  Butterfly12Hatched: 'Butterfly12Hatched',
  Butterfly13Hatched: 'Constela butterfly larva',
  Butterfly14Hatched: 'Butterfly14Hatched',
  Butterfly15Hatched: 'Butterfly15Hatched',
  Butterfly16Hatched: 'Butterfly16Hatched',
  Butterfly17Hatched: 'Butterfly17Hatched',
  Butterfly18Hatched: 'Butterfly18Hatched',
  Butterfly19Hatched: 'Butterfly19Hatched',
  Butterfly1Hatched: 'Butterfly1Hatched',
  Butterfly20Hatched: 'Butterfly20Hatched',
  Butterfly20Larvae: 'Oesbe butterfly larva',
  Butterfly2Hatched: 'Butterfly2Hatched',
  Butterfly3Hatched: 'Butterfly3Hatched',
  Butterfly4Hatched: 'Butterfly4Hatched',
  Butterfly5Hatched: 'Butterfly5Hatched',
  Butterfly6Hatched: 'Butterfly6Hatched',
  Butterfly7Hatched: 'Butterfly7Hatched',
  Butterfly8Hatched: 'Butterfly8Hatched',
  Butterfly9Hatched: 'Butterfly9Hatched',
  ButterflyFarm2: 'T2 Butterfly FarmInsert butterfly larvae to increase insects levels',
  ButterflyFarm3: 'T3 Butterfly FarmInsert butterfly larvae to increase insects levels',
  Chair2: 'Cozy chair',
  ChlorineCapsule1: 'Chlorine dioxide',
  CircuitBoard1: 'Circuit board',
  Container3: 'T2 Locker Storage',
  ContainerAqualis: 'Clam',
  ContainerGoldenAqualis: 'Golden clam',
  ContainerToxic1: 'Toxic goo storage',
  CookCake1: 'Birthday cake',
  CookChocolate: 'Chocolate',
  CookCocoaGrowable: 'Cocoa',
  CookCookie1: 'Chocolate cookie',
  CookCroissant: 'Croissant',
  CookFlour: 'Flour',
  CookingStation1: 'Cooking station',
  CookStew1: 'Honey cooked beans',
  CookStewFish1: 'Fish soup',
  CookWheatGrowable: 'Wheat',
  CosmicQuartz: 'Cosmic Quartz',
  Counter1: 'Countertop T1',
  Counter2: 'Countertop T2',
  DebrisContainer1: 'Debris',
  DeparturePlatform: 'Extraction platform',
  Desktop2: 'Desktop T2',
  DetoxificationMachine1: 'Detoxification machine T1',
  DetoxificationMachine2: 'Detoxification machine T2',
  DetoxificationMachine3: 'Detoxification machine T3',
  DNASequence: 'Creature DNA',
  Dolomite: 'Dolomite',
  DroneExplodable: 'DroneExplodable',
  DroneLog: 'Drone Log',
  DroneStation1: 'Drone station',
  Ecosystem1: 'Ecosystem',
  Elevator: 'Elevator',
  EndingExplosives: 'Large explosive device',
  EscapePodHumble: 'EscapePodHumble',
  EscapePodInterplanetary: 'EscapePodInterplanetary',
  EscapePodToxicity: 'EscapePodToxicity',
  ExerciseBike1: 'Indoor bike',
  Explosive: 'Explosive',
  Fabric: 'Blue fabric',
  Farm2: 'Outdoor farm T2',
  Faucet1: 'Faucet',
  Fence: 'Fence',
  Fertilizer3: 'Fertilizer T3',
  Fireplace: 'Fireplace',
  Fish10Hatched: 'Fish10Hatched',
  Fish11Hatched: 'Fish11Hatched',
  Fish12Eggs: 'Velkia fish eggs',
  Fish12Hatched: 'Fish12Hatched',
  Fish13Eggs: 'Galbea fish eggs',
  Fish13Hatched: 'Fish13Hatched',
  Fish14Eggs: 'Stabu fish eggs',
  Fish14Hatched: 'Fish14Hatched',
  Fish15Eggs: 'Atabu fish eggs',
  Fish15Hatched: 'Fish15Hatched',
  Fish1Hatched: 'Fish1Hatched',
  Fish2Hatched: 'Fish2Hatched',
  Fish3Hatched: 'Fish3Hatched',
  Fish4Hatched: 'Fish4Hatched',
  Fish5Hatched: 'Fish5Hatched',
  Fish6Hatched: 'Fish6Hatched',
  Fish7Hatched: 'Fish7Hatched',
  Fish8Hatched: 'Fish8Hatched',
  Fish9Hatched: 'Fish9Hatched',
  FishDisplayer1: 'Fish display',
  FishFarm1: 'Fish farm',
  FishFarm2: 'Fish farm T2',
  Flare: 'Flare',
  FoundationAngle: 'Foundation – Angle',
  FoundationSlope: 'Foundation – Slope',
  FountainBig: 'Fountain',
  Fridge1: 'Fridge',
  Frog10Hatched: 'Frog10Hatched',
  Frog11Eggs: 'Lavaum frog eggs',
  Frog11Hatched: 'Frog11Hatched',
  Frog12Eggs: 'Leglus frog eggs',
  Frog12Hatched: 'Frog12Hatched',
  Frog13Eggs: 'Jumi frog eggs',
  Frog13Hatched: 'Frog13Hatched',
  Frog14Eggs: 'Seren frog eggs',
  Frog14Hatched: 'Frog14Hatched',
  Frog15Eggs: 'Acuzzi frog eggs',
  Frog15Hatched: 'Frog15Hatched',
  Frog16Eggs: 'Toxifia frog eggs',
  Frog16Hatched: 'Frog16Hatched',
  Frog1Hatched: 'Frog1Hatched',
  Frog2Hatched: 'Frog2Hatched',
  Frog3Hatched: 'Frog3Hatched',
  Frog4Hatched: 'Frog4Hatched',
  Frog5Hatched: 'Frog5Hatched',
  Frog6Hatched: 'Frog6Hatched',
  Frog7Hatched: 'Frog7Hatched',
  Frog8Hatched: 'Frog8Hatched',
  Frog9Hatched: 'Frog9Hatched',
  FrogDisplayer1: 'Frog displayerInsert a frog egg to display a frog',
  FrogGoldEggs: 'Golden frog eggs',
  FrogGoldHatched: 'FrogGoldHatched',
  FuseCartridge: 'Fuse cartridge',
  FusePurification1: 'Purification multiplier fuse',
  GasExtractor2: 'Gas Extractor T2',
  GenerationGroupVein: 'GenerationGroupVein',
  GeneticExtractor1: 'Genetic extractor',
  GeneticSynthetizer1: 'Genetic synthesizer',
  GeneticTrait: 'Genetic trait',
  GoldenEffigie4: 'Golden effigy 4',
  GoldenEffigie5: 'Golden effigy 5',
  GoldenEffigie6: 'Golden effigy 6',
  GoldenEffigie7: 'Golden effigy 7',
  GoldenEffigie8: 'Golden effigy 8',
  GoldenEffigie9: 'Golden effigy 9',
  GoldenToxicityEffigie1: 'Golden effigy 1',
  GoldenToxicityEffigie2: 'Golden effigy 2',
  GoldenToxicityEffigie3: 'Golden effigy 3',
  GoldenToxicityEffigie4: 'Golden effigy 4',
  GoldenToxicityEffigie5: 'Golden effigy 5',
  GoldenToxicityEffigie6: 'Golden effigy 6',
  HarvestingRobot1: 'Harvesting robot',
  Heater5: 'Heater T5',
  HologramGenerator: 'Hologram projector',
  honey: 'Honey',
  HudChipCleanConstruction: 'Microchip – Construction menu filter',
  InteriorStairs1: 'Interior stairs',
  InterplanetaryExchangePlatform1: 'Interplanetary exchange shuttleAllows you to retrieve any resources you have on other planets',
  KeyCard2: 'Access card 2',
  Library1: 'Library',
  LightBoxMedium: 'Light Box',
  Megadome1: 'Megadome',
  MicroPlastics: 'Microplastics',
  'Minable-Tungsten': 'Tungsten',
  MultiToolCleaningGooChip1: 'Microchip – T1 Goo cleaning',
  MultiToolCleaningGooChip2: 'Microchip – T2 Goo cleaning',
  MultiToolCleaningGooChip3: 'Microchip – T3 Goo cleaning',
  MultiToolCleaningGooChip4: 'Microchip – T4 Goo cleaning',
  MultiToolLight3: 'Microchip – T3 Torch',
  NitrogenCapsule1: 'Nitrogen cartridge',
  Obsidian: 'Obsidian',
  Optimizer1: 'Machine optimizer T1',
  Optimizer2: ' Machine Optimizer T2',
  OreBreaker1: ' Ore Crusher T1',
  OreBreaker2: ' Ore Crusher T2',
  OreBreaker3: ' Ore Crusher T3',
  OreExtractor3: 'Ore Extractor T3',
  Phosphorus: 'Phosphorus',
  Phytoplankton4: 'Phytoplankton D',
  PlanetaryDeliveryDepot1: 'Planetary Delivery Depot',
  PlanetViewer1: 'Planet viewer',
  PlasticPolymer: 'Plastic polymer',
  Pod9xA: 'Rounded living compartment',
  Pod9xB: 'Living compartment with dome',
  Pod9xC: '3x3 Living compartment',
  PortalGenerator1: 'Portal generator',
  Poster1: 'Poster A',
  Poster10: 'Poster J',
  Poster11: 'Poster K',
  Poster12: 'Poster L',
  Poster13: 'Poster M',
  Poster2: 'Poster B',
  Poster3: 'Poster C',
  Poster4: 'Poster D',
  Poster5: 'Poster E',
  Poster6: 'Poster F',
  Poster7: 'Poster G',
  Poster8: 'Poster H',
  Poster9: 'Poster I',
  PristineMushroom: 'Pristine mushroom',
  ProceduralInstanceGenerator: 'ProceduralInstanceGenerator',
  ProceduralWreckContainer1: 'Storage crate T1',
  ProceduralWreckContainer2: 'Storage crate T2',
  ProceduralWreckSafe: 'Big safe',
  PurificationCapsule: 'Purification capsule',
  PurificationGel: 'Purification gel',
  PurifiedWater: 'Purified water',
  QuartzCraftStation1: 'Quartz craft station',
  RecyclingMachine2: ' Recycling machine T2',
  RocketAnimals1: 'Animals spreader rocket',
  RocketBiomass2: ' Plant Rocket T2',
  RocketDeparture1: 'Extraction rocket',
  RocketDrones1: 'Drone visualization rocket',
  RocketHeat2: 'Asteroid attraction rocket T2',
  RocketInformations2: 'Map information rocket T2',
  RocketInsects1: 'Insect spreader rocket',
  RocketInsects2: 'Insect spreader rocket T2',
  RocketMap4: 'GPS Satellite T4',
  RocketPressure2: 'Magnetic field protection rocket T2',
  RocketPurification1: 'Purification rocket',
  RocketReactor2: 'Rocket Engine T2',
  RocketToxicInformations1: 'Toxic area information rocket',
  RocketTravel1: 'Interplanetary travel rocket',
  RockExplodable: 'Explodable Rock',
  'Rod-tungsten': 'Tungsten Rod',
  ScreenBiomass: 'Biomass screen',
  ScreenSystem1: 'Solar system screen',
  ScreenToxic1: 'Screen – Toxicity',
  Seed10Humble: 'Furteo Seed',
  Seed10HumbleGrowable: 'Seed10HumbleGrowable',
  Seed11Humble: 'Humblea Seed',
  Seed11HumbleGrowable: 'Seed11HumbleGrowable',
  Seed7HumbleGrowable: 'Seed7HumbleGrowable',
  Seed8HumbleGrowable: 'Seed8HumbleGrowable',
  Seed9HumbleGrowable: 'Seed9HumbleGrowable',
  Selenium: 'Selenium',
  Shelves1: 'Shelves',
  'Skin-01': 'Spacesuit Comto',
  'Skin-02': 'Spacesuit Blasto',
  'Skin-03': 'Spacesuit Primo',
  'Skin-04': 'Spacesuit Goldeo',
  'Skin-05': 'Spacesuit Scifo',
  'Skin-06': 'Spacesuit Cipto',
  'Skin-07': 'Spacesuit Beteo',
  'Skin-08': 'Spacesuit Tureo',
  'Skin-09': 'Spacesuit Fablo',
  'Skin-10': 'Spacesuit Tubio',
  'Skin-11': 'Spacesuit Vateo',
  'Skin-12': 'Spacesuit Widio',
  'Skin-13': 'Spacesuit Mekio',
  'Skin-14': 'Spacesuit Abyso',
  'Skin-15': 'Spacesuit Ettio',
  'Skin-16': 'Spacesuit Plesao',
  'Skin-17': 'Spacesuit Rorao',
  'Skin-18': 'Spacesuit Starforma',
  'Skin-19': 'Spacesuit Glitx',
  'Skin-20': 'Spacesuit Colonnya',
  'Skin-21': 'Spacesuit Sunsio',
  'Skin-22': 'Spacesuit Goox',
  'Skin-23': 'Spacesuit Alij',
  SkinDisplayer: 'Spacesuit Displayer',
  SmartFabric: 'Smart fabric',
  SofaColored: 'Customizable sofa',
  SpaceMultiplierAnimals: 'SpaceMultiplierAnimals',
  SpaceMultiplierInsects: 'SpaceMultiplierInsects',
  SpaceMultiplierPlants: 'SpaceMultiplierPlants',
  SpaceMultiplierPurification: 'SpaceMultiplierPurification',
  StarformContainer: 'Starform Crate',
  StarformEffigie1: 'Starform Effigy 1',
  StarformEffigie2: 'Starform Effigy 2',
  StarformEffigie3: 'Starform Effigy 3',
  StarformEffigie4: 'Starform Effigy 4',
  StarformEffigie5: 'Starform Effigy 5',
  StarformEffigie6: 'Starform Effigy 6',
  Table1: 'Big table',
  TableSmall3: 'Glass table',
  ToxicGoo: 'Toxic Goo',
  ToxicityAmmo: 'Toxic artillery shell',
  ToxicityAmmoPack: 'Toxic artillery shells pack',
  ToxicityDiorama1: 'Terraforming Diorama A',
  ToxicityDiorama2: 'Terraforming Diorama B',
  ToxicityMedecine: 'Pristine purifying balm',
  ToxicityMedecinePack: 'Pristine purifying balms pack',
  ToxicRefinementCraftStation1: 'Craft Station - refinement',
  ToxicSpores: 'Toxic Spores',
  ToxicWater: 'Toxic water',
  ToxicWaterCollector1: 'Toxic Water Collector T1',
  ToxicWaterCollector2: 'Toxic Water Collector T2',
  ToxicWaterCollector3: 'Toxic Water Collector T3',
  ToxicZoneHudDisplayer: 'Microchip - Toxic Areas Informations',
  ToxicZoneHudDisplayer2: 'Microchip – Toxic Areas Informations T2',
  Toxins: 'Toxins',
  ToxinsFilter1: 'Toxins Filter T1',
  ToxinsFilter2: 'Toxins Filter T2',
  ToxinsFilter3: 'Toxins Filter T3',
  TradePlatform1: 'Trade space rocket',
  TrashAluminiumScraps1: 'Aluminum scraps',
  Trashcan1: 'Trash can',
  TrashElectronics1: 'Electronics scraps',
  TrashMetalsCanisters1: 'Metal canister',
  TrashMetalsScraps1: 'Metal scraps',
  TrashUraniumScraps1: 'Uranium scraps',
  Treadmill1: 'Treadmill',
  TreePlanter: 'Tree pot',
  Uraninite: 'Uraninite',
  Vault1: 'Safe Vault',
  VehicleBeacon1: 'Vehicle – Beacon',
  VehicleCrafter1: 'Vehicle station',
  VehicleEquipmentSize1: 'Vehicle – T1 Equipment increase',
  VehicleEquipmentSize2: 'Vehicle – T2 Equipment increase',
  VehicleInventorySize1: 'Vehicle – T1 Inventory increase',
  VehicleInventorySize2: 'Vehicle – T2 Inventory increase',
  VehicleInventorySize3: 'Vehicle – T3 Inventory increase',
  VehicleLights1: 'Vehicle – T1 Lights',
  VehicleLights2: 'Vehicle – T2 Lights',
  VehicleLogistic1: 'Vehicle – Logistics',
  VehicleOxygen1: 'Vehicle – Unlimited oxygen',
  VehicleSpeed1: 'Vehicle – T1 Speed increase',
  VehicleSpeed2: 'Vehicle – T2 Speed increase',
  VehicleSpeed3: 'Vehicle – T3 Speed increase',
  VehicleSpeed4: 'Vehicle – T4 Speed increase',
  VehicleTruck: 'Vehicle – Rover',
  WallInside: 'Interior wall',
  WardenAustel: 'Warden\'s altar',
  WardensChip: 'Warden\'s key detector',
  WaterLifeCollector1: 'Water life collector',
  WindTurbine1: 'Wind turbine T2',
  WreckEntryLocked1: 'Access Console T1 (wreck)',
  WreckEntryLocked2: 'Access Console T2 (wreck)',
  WreckFusionGenerator: 'Fusion reactor (wreck)',
  WreckRockExplodable: 'WreckRockExplodable',
  WreckSafe: 'Big safe',
  WreckServer: 'Technical debris',
  WreckWardrobe: 'Spacesuits locker',
} as const;

export type WorldObjectName = keyof typeof worldObjectLabels;

export type WorldObjectLabel = typeof worldObjectLabels[WorldObjectName];
